name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/kubesphere/kube-apiserver:v1.28.0 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/kube-apiserver:v1.28.0
         skopeo copy docker://docker.io/kubesphere/kube-controller-manager:v1.28.0 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/kube-controller-manager:v1.28.0
         skopeo copy docker://docker.io/kubesphere/kube-scheduler:v1.28.0 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/kube-scheduler:v1.28.0
         skopeo copy docker://docker.io/kubesphere/kube-proxy:v1.28.0 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/kube-proxy:v1.28.0
         skopeo copy docker://docker.io/kubesphere/pause:3.8 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/pause:3.8
         skopeo copy docker://docker.io/kubesphere/etcd:3.5.9-0 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/etcd:3.5.9-0
         skopeo copy docker://docker.io/coredns/coredns:1.10.1 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/coredns:v1.10.1
         skopeo copy docker://docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel2 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/flannel-cni-plugin:v1.5.1-flannel2
         skopeo copy docker://docker.io/flannel/flannel:v0.25.6 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/flannel:v0.25.6
