name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/kubesphere/pause:3.9 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/pause:3.9
         skopeo copy docker://docker.io/kubesphere/etcd:3.5.15-0 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/etcd:3.5.15-0
         skopeo copy docker://docker.io/coredns/coredns:1.11.3 docker://crpi-colml5x7wigtexnt.cn-shenzhen.personal.cr.aliyuncs.com/lengong/coredns:1.11.3
         
